#!/bin/bash

PICS=~/Pictures
VIDS=~/Videos
MUSIC=~/Music

images='*.jpg *.png *.gif *.svg'

for i in $images
do
find . -maxdepth 1 -iname $i -type f -print -exec mv {} $PICS \;
done

videos='*.mp4 *.m4v *.avi *.mpeg'
for i in $videos
do
find . -maxdepth 1 -iname $i -type f -print -exec mv {} $VIDS \;
done

music='*.jpg *.ogg *.flac *.mp3  *.wav'
for i in $music
do
find . -maxdepth 1 -iname $i -type f -print -exec mv {} $MUSIC \;
done


