#!/bin/bash
# taken from http://askubuntu.com/questions/80638/how-to-disable-auto-power-off-of-usb-devices-like-usb-mouse

for i in /sys/bus/usb/devices/*/power/autosuspend;
    do echo 2 > $i;
done

for i in /sys/bus/usb/devices/*/power/level;
    do echo on > $i;
done
