#!/bin/bash
if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
  echo "Usage: `basename $0` [FILE]"
    exit 0
fi

INPATH="$1"
WD=`pwd`
lastchar=${INPATH: -1:1}

if [ "$lastchar" == "/" ];
then
	INPATH=${INPATH: 0:${#INPATH}-1}
	echo "tarenc: Removing trailing \"/\" from path"
fi

echo "tarenc: Creating \"$INPATH.tar.gz.gpg\""
# Attempt to prevent GPG pinentry gui from appearing
export DISPLAY=""
tar zcf - "$INPATH" | gpg -c > "$INPATH.tar.gz.gpg"

